# Generated by Django 3.2.7 on 2021-09-15 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('Restaurant Name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('borough', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='must be a value from 1-5')])),
                ('xcor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('storytext', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.restaurants')),
            ],
        ),
    ]
