# Generated by Django 3.2.7 on 2021-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='restaurants',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='ycor',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
    ]
