# Generated by Django 3.2.7 on 2021-09-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210917_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='Restaurant Name',
            new_name='name',
        ),
    ]
