# Generated by Django 3.2.7 on 2021-09-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='xcor',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='ycor',
            new_name='lon',
        ),
    ]
